import type { NextPage } from 'next'
import Head from 'next/head'
import Navbar from '../components/Navbar'
import styles from '../styles/Home.module.scss'
import Calculator from '../components/Calculator'

const Home: NextPage = () => {
  return (
    <div id={styles.main}>
      <Head>
        <title>Mass Loop</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <Calculator />
    </div>
  )
}

export default Home
