import type { NextPage } from 'next'
import { useLanguage } from '../contexts/LanguageContext'
import Image from 'next/image'
import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import Navbar from '../components/Navbar'
import Calculator from '../components/Calculator'
import ShoppingBag from '../public/images/shoppingBag.svg'
import textsData from '../texts.json'
import { useEffect, useState } from 'react'

const Home: NextPage = () => {
  const { language } = useLanguage()
  const [width, setWidth] = useState<number | null | undefined>()
  // @ts-expect-error
  const text = textsData[language]
  // @ts-expect-error
  const desktop = width >= 1024

  useEffect(() => {
    const updateWidth = () => {
      const newWidth = window.innerWidth
      setWidth(newWidth)
    }
    window.addEventListener('load', updateWidth)
    window.addEventListener('resize', updateWidth)
    return () => window.removeEventListener('resize', updateWidth)
  }, [])

  return (
    <div id={styles.main}>
      <Head>
        <title>Mass Loop</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <span id='#' />
      <Navbar width={width} />
      <span id='about' />
      <div id={styles.upperSection}>
        <h1>{text.title}</h1>
        <div id={styles.image}>
          {!desktop && (
            <button>
              <Image
                src={ShoppingBag}
                alt='buy button'
                width={28.89}
                height={45.28}
              />
            </button>
          )}
        </div>
        <div id={styles.textSection}>
          <h2>Płać 5 razy mniej za wywóz odpadów szklanych.</h2>
          <p>
            Kruszarka zmniejsza gabaryty szklanych śmieci, a Ty płacisz
            PIĘ-CIO-KROT-NIE niższe rachunki za ich wywóz.
          </p>
        </div>
        <span id='calc' />
      </div>
      <Calculator />
      <div id={styles.bottomSection}>
        <p>To na co wydasz zaoszczędzoną gotówkę?</p>
        <button>
          <h3>KUP</h3> 8499 zł
        </button>
        <h3>Brzmi dobrze? Uważaj. Dopiero się rozkręcamy!</h3>
      </div>
    </div>
  )
}

export default Home
